DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


LINODE_BUCKET = 'resources-cpat1'
LINODE_BUCKET_REGION = 'us-east-1'
LINODE_BUCKET_ACCCESS_KEY = '7ARK0BNLY093WYS4IA81'
LINODE_BUCKET_SECRET_KEY = 'vEk6kpfIN5lDuw5ugAphLXZcMSQL9pdXXcy5mJF1'



AWS_S3_ENDPOINT_URL = f'https://{LINODE_BUCKET_REGION }.linodeobjects.com'
AWS_ACCESS_KEY_ID = LINODE_BUCKET_ACCCESS_KEY
AWS_SECRET_ACCESS_KEY = LINODE_BUCKET_SECRET_KEY
AWS_S3_REGION_NAME = LINODE_BUCKET_REGION
AWS_S3_USE_SSL = True
AWS_STORAGE_BUCKET_NAME = LINODE_BUCKET

print(f"from cpat setup folder {LINODE_BUCKET}")